language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
  - pip install coverage codecov
script:
  - coverage run --parallel-mode --concurrency=multiprocessing test_parmap.py
  - coverage combine
  - coverage report
after_success:
  - codecov

