package:
  name: parmap
  version: !!str 1.5.2

source:
  fn: parmap-1.5.2.tar.gz
  url: https://files.pythonhosted.org/packages/c5/57/0fafe2d6a750ae94bc4d0191eb60002d16a1393fd343041c768eb54ceaf9/parmap-1.5.2.tar.gz
  sha256: a15f33fa0e2a454f29aecfdd5a825c780b7d26d876eb6093476ddf5c47c8f9b9

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"


requirements:
  host:
    - python
    - pip
  run:
    - python
    - tqdm # optional dependency

test:
  # Python imports
  imports:
    - parmap

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/zeehio/parmap
  license: APACHE

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
