package:
  name: parmap
  version: !!str 1.4.0

source:
  fn: parmap-1.4.0.tar.gz
  url: https://pypi.python.org/packages/6e/d2/400781417eaf123e5ff394ce428dc3e4175f6065b1f20ed5f6d6a3307210/parmap-1.4.0.tar.gz

requirements:
  build:
    - python

  run:
    - python
    - tqdm # optional dependency

test:
  # Python imports
  imports:
    - parmap

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/zeehio/parmap
  license: Apache Software License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
