package:
  name: parmap
  version: !!str 1.5.0

source:
  fn: parmap-1.5.0.tar.gz
  url: https://pypi.python.org/packages/df/54/b2d3241ce0ea6dbb211e5835bd5bed1c786b3f756e9d230a2c1ff5f57f30/parmap-1.5.0.tar.gz#md5=373163e995029556398201085fba67c5

requirements:
  build:
    - python

  run:
    - python
    - tqdm # optional dependency

test:
  # Python imports
  imports:
    - parmap

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/zeehio/parmap
  license: Apache Software License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
